import React from 'react'

const StarSVG = () => {
  return (
    <svg viewBox='0 0 925 425'>
        <g>
            <circle 
            className="cir" 
            fill="#fff" 
            cx={150} 
            cy={200} 
            r={2} 
            fillOpacity={0.4} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={250} 
            cy={240} 
            r={2} 
            fillOpacity={0.5} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={350} 
            cy={200} 
            r={3} 
            fillOpacity={0.3} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={170} 
            cy={250} 
            r={2} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={150} 
            cy={300} 
            r={3} 
            fillOpacity={0.8} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={200} 
            cy={290} 
            r={3} 
            fillOpacity={0.8} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={70} 
            cy={380} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={170} 
            cy={400} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={240} 
            cy={350} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={470} 
            cy={380} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={570} 
            cy={350} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={670} 
            cy={370} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={770} 
            cy={350} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={870} 
            cy={390} 
            r={3} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={830} 
            cy={310} 
            r={2} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={730} 
            cy={310} 
            r={3} 
            fillOpacity={0.5} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={630} 
            cy={310} 
            r={3} 
            fillOpacity={0.6} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={530} 
            cy={310} 
            r={2} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={730} 
            cy={200} 
            r={2} 
            fillOpacity={0.5} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={630} 
            cy={240} 
            r={2} 
            fillOpacity={0.8} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={430} 
            cy={140} 
            r={2} 
            fillOpacity={0.9} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={430} 
            cy={240} 
            r={2} 
            fillOpacity={0.9} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={330} 
            cy={340} 
            r={3} 
            fillOpacity={0.9} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={530} 
            cy={100} 
            r={1} 
            fillOpacity={0.7} 
            />
            <circle 
            className="cir" 
            fill="#fff" 
            cx={630} 
            cy={150} 
            r={1} 
            fillOpacity={0.6} 
            />
        </g>
    </svg>
  )
}

export default StarSVG;